spring:
  config:
    import: optional:nacos:anju-pure-backend.yml
  application:
    name: anju-pure-backend
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_ADDR:localhost:8848}
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yml
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}
  datasource:
    url: jdbc:mysql://localhost:3306/anju_ops?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: INFO
